export default [
    {
        "id": "1",
        "slug": "blade-1",
        "title": "Blade",
        "year": "1998",
        "rated": "7.6",
        "released": "21 Aug 1998",
        "runtime": "120 min",
        "genre": "Action, Horror, Sci-Fi",
        "director": "Stephen Norrington",
        "writer": "David S. Goyer",
        "actors": "Wesley Snipes, Stephen Dorff, Kris Kristofferson, N'Bushe Wright",
        "description": "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
        "language": "English, Russian, Serbian",
        "country": "USA",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg",
        "links": [
            'https://r1---sn-npoe7n7z.googlevideo.com/videoplayback?expire=1578390826&ei=CTkUXojZDcWErQSRwJrABw&ip=14.177.235.12&id=cbe59c0c45934a95&itag=22&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-npoe7n7z&ms=nxu&mv=m&mvi=0&pl=24&sc=yes&susc=ph&app=fife&mime=video/mp4&dur=7217.110&lmt=1433243106097196&mt=1578383546&sparams=expire,ei,ip,id,itag,source,requiressl,susc,app,mime,dur,lmt&sig=ALgxI2wwRQIgYsyI7H2DhqejSv31WjhPZoNk4CPLFZWFJJACSNn543gCIQCVaSzjkkewuP_Z8G9NOOd3V3LRVb-V6AolL_YxIDbFiw==&lsparams=mm,mn,ms,mv,mvi,pl,sc&lsig=AHylml4wRQIgeStEo6mQO4kpXmS3FfBHD_Xxb46xRwMrCwDWABvPwVECIQDVja2WUgsIX3OZSMW32mVzulLpG3cQSAB0llfwmupsXg=='
        ],
        "trailer": "https://www.youtube.com/watch?v=kaU2A7KyOu4",
        "production": "New Line Cinema",
    },{
        "id": "2",
        "slug": "blade-2",
        "title": "Blade",
        "year": "1998",
        "rated": "7.6",
        "released": "21 Aug 1998",
        "runtime": "120 min",
        "genre": "Action, Horror, Sci-Fi",
        "director": "Stephen Norrington",
        "writer": "David S. Goyer",
        "actors": "Wesley Snipes, Stephen Dorff, Kris Kristofferson, N'Bushe Wright",
        "description": "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
        "language": "English, Russian, Serbian",
        "country": "USA",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg",
        "links": [
            'https://r1---sn-npoe7n7z.googlevideo.com/videoplayback?expire=1578390826&ei=CTkUXojZDcWErQSRwJrABw&ip=14.177.235.12&id=cbe59c0c45934a95&itag=22&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-npoe7n7z&ms=nxu&mv=m&mvi=0&pl=24&sc=yes&susc=ph&app=fife&mime=video/mp4&dur=7217.110&lmt=1433243106097196&mt=1578383546&sparams=expire,ei,ip,id,itag,source,requiressl,susc,app,mime,dur,lmt&sig=ALgxI2wwRQIgYsyI7H2DhqejSv31WjhPZoNk4CPLFZWFJJACSNn543gCIQCVaSzjkkewuP_Z8G9NOOd3V3LRVb-V6AolL_YxIDbFiw==&lsparams=mm,mn,ms,mv,mvi,pl,sc&lsig=AHylml4wRQIgeStEo6mQO4kpXmS3FfBHD_Xxb46xRwMrCwDWABvPwVECIQDVja2WUgsIX3OZSMW32mVzulLpG3cQSAB0llfwmupsXg=='
        ],
        "trailer": "https://www.youtube.com/watch?v=kaU2A7KyOu4",
        "production": "New Line Cinema",
    },{
        "id": "3",
        "slug": "blade-3",
        "title": "Blade",
        "year": "1998",
        "rated": "7.6",
        "released": "21 Aug 1998",
        "runtime": "120 min",
        "genre": "Action, Horror, Sci-Fi",
        "director": "Stephen Norrington",
        "writer": "David S. Goyer",
        "actors": "Wesley Snipes, Stephen Dorff, Kris Kristofferson, N'Bushe Wright",
        "description": "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
        "language": "English, Russian, Serbian",
        "country": "USA",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg",
        "links": [
            'https://r1---sn-npoe7n7z.googlevideo.com/videoplayback?expire=1578390826&ei=CTkUXojZDcWErQSRwJrABw&ip=14.177.235.12&id=cbe59c0c45934a95&itag=22&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-npoe7n7z&ms=nxu&mv=m&mvi=0&pl=24&sc=yes&susc=ph&app=fife&mime=video/mp4&dur=7217.110&lmt=1433243106097196&mt=1578383546&sparams=expire,ei,ip,id,itag,source,requiressl,susc,app,mime,dur,lmt&sig=ALgxI2wwRQIgYsyI7H2DhqejSv31WjhPZoNk4CPLFZWFJJACSNn543gCIQCVaSzjkkewuP_Z8G9NOOd3V3LRVb-V6AolL_YxIDbFiw==&lsparams=mm,mn,ms,mv,mvi,pl,sc&lsig=AHylml4wRQIgeStEo6mQO4kpXmS3FfBHD_Xxb46xRwMrCwDWABvPwVECIQDVja2WUgsIX3OZSMW32mVzulLpG3cQSAB0llfwmupsXg=='
        ],
        "trailer": "https://www.youtube.com/watch?v=kaU2A7KyOu4",
        "production": "New Line Cinema",
    },{
        "id": "4",
        "slug": "blade-4",
        "title": "Blade",
        "year": "1998",
        "rated": "7.6",
        "released": "21 Aug 1998",
        "runtime": "120 min",
        "genre": "Action, Horror, Sci-Fi",
        "director": "Stephen Norrington",
        "writer": "David S. Goyer",
        "actors": "Wesley Snipes, Stephen Dorff, Kris Kristofferson, N'Bushe Wright",
        "description": "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
        "language": "English, Russian, Serbian",
        "country": "USA",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg",
        "links": [
            'https://r1---sn-npoe7n7z.googlevideo.com/videoplayback?expire=1578390826&ei=CTkUXojZDcWErQSRwJrABw&ip=14.177.235.12&id=cbe59c0c45934a95&itag=22&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-npoe7n7z&ms=nxu&mv=m&mvi=0&pl=24&sc=yes&susc=ph&app=fife&mime=video/mp4&dur=7217.110&lmt=1433243106097196&mt=1578383546&sparams=expire,ei,ip,id,itag,source,requiressl,susc,app,mime,dur,lmt&sig=ALgxI2wwRQIgYsyI7H2DhqejSv31WjhPZoNk4CPLFZWFJJACSNn543gCIQCVaSzjkkewuP_Z8G9NOOd3V3LRVb-V6AolL_YxIDbFiw==&lsparams=mm,mn,ms,mv,mvi,pl,sc&lsig=AHylml4wRQIgeStEo6mQO4kpXmS3FfBHD_Xxb46xRwMrCwDWABvPwVECIQDVja2WUgsIX3OZSMW32mVzulLpG3cQSAB0llfwmupsXg=='
        ],
        "trailer": "https://www.youtube.com/watch?v=kaU2A7KyOu4",
        "production": "New Line Cinema",
    },
]
;